DROP TABLE IF EXISTS infracoes CASCADE;

DROP TABLE IF EXISTS veiculos CASCADE;

DROP TABLE IF EXISTS telefones CASCADE;

DROP TABLE IF EXISTS proprietarios CASCADE;

DROP TABLE IF EXISTS condutores CASCADE;

DROP TABLE IF EXISTS tipos_de_infracoes CASCADE;

DROP TABLE IF EXISTS agentes_de_transito CASCADE;

DROP TABLE IF EXISTS locais CASCADE;

DROP TABLE IF EXISTS categorias CASCADE;

DROP TABLE IF EXISTS modelos CASCADE;

DROP TABLE IF EXISTS pessoas CASCADE;